# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file


version: 2
updates:
  - package-ecosystem: "maven" # กำหนดว่าใช้ Maven
    directory: "/" # ระบุที่อยู่ของโปรเจกต์ (ที่อยู่ของไฟล์ pom.xml)
    schedule:
      interval: "weekly" # กำหนดการตรวจสอบทุกสัปดาห์
    commit-message:
      prefix: "deps" # ระบุคำที่จะแสดงใน commit message เช่น "deps: update"
