spring:
  application:
    name: crud

  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: syspass

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB

  messages:
    basename: messages